### ISSUE TITLE
RFC: Twitter PinBot using IPFS Cluster in Golang

### ISSUE THREAD

**Issue by vasa-develop** [simpleaswater/rfcs#27]
**What new topic/thread/tutorial are you proposing? Please describe.**
A Step-by-Step walkthrough of hector's [twitter-pinbot](https://github.com/hsanjuan/twitter-pinbot).
This includes:

- building a twitter bot.
- listening to the tweets of which mention "@simpleaswater_" twitter account.
- parsing the tweet to add, pin or unpin any data.
- setting up an IPFS Cluster network.
- connecting the twitter bot to the IPFS Cluster setup.

**Comment by vasa-develop** [comment]
Just got the pinbot [working](https://twitter.com/vasa_develop/status/1215943512140607489)

**Comment by 0zAND1z** [comment]
Looks like another SAW article is on its way ❤️

**Comment by vasa-develop** [comment]
Almost getting this one closed: https://github.com/simpleaswater/twitter-pinbot
Will publish the article by tomorrow.

**Comment by vasa-develop** [comment]
Done.
https://simpleaswater.com/ipfs-cluster-twitter-pinbot/
