### ISSUE TITLE
RFC: IpfsDB dapp usage tutorial

### ISSUE THREAD

**Issue by vaultec81** [simpleaswater/rfcs#62]
**Basic Dapp using IpfsDB as a database.**
> IpfsDB aims to bring MongoDB-like developer interface to Web 3.0.

Provide a tutorial teaching viewers how to build a very basic dapp utilizing the IpfsDb database. (Note the name is subject to change. It is only a place holder). The tutorial must include basic setup, using the blockchain for database consensus, logic behind Ipfsdb/orbitdb including some explanation on how the APIs work behind the scenes for developers, common issues a developer may come across, and how to solve or circumvent the issue.

**Comment by vasa-develop** [comment]
https://simpleaswater.com/tag/aviondb/
